// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

type Env = {
  DATABASE_URI: string;
};

const env: Env = {
  DATABASE_URI: process.env.DATABASE_URI as string,
};

if (!env.DATABASE_URI) {
  console.error("DATABASE_URI is not defined in the environment variables.");
  process.exit(1);
}
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.DATABASE_URI,
  },
});
