// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {DATABASE_URI} from "./src/config/env.js";

if (!DATABASE_URI) {
  console.error("DATABASE_URI is not defined in the environment variables.");
  process.exit(1);
}
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URI,
  },
});
